name = "defcxz"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
cwd = "."

[[pages_builds]]
build_command = "npm run build"
build_output_directory = "dist"

[assets]
directory = "./dist"