name = "defcxz"
compatibility_date = "2024-01-15"

[build]
command = "npm run build:cf"
cwd = "."

[build.environment_variables]
NODE_VERSION = "22"
NPM_CONFIG_OPTIONAL = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"

[[pages_builds]]
build_command = "npm run build:cf"
build_output_directory = "dist"
