import "~/styles/globals.css";

import { GeistSans } from "geist/font";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import React from "react";

export const metadata = {
  title: "Mario G. | defcxz",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
